name: build
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        go: ["tip"]
        go-amd64: ["v1", "v2", "v3"]
        target:
          - "juju/juju"
          - "kubernetes/ingress-nginx"
          - "hashicorp/terraform"
          - "hashicorp/consul"
          - "hashicorp/vault"
          - "hashicorp/nomad"
          - "hashicorp/packer"
          - "hashicorp/boundary"
          - "hashicorp/waypoint"
          - "prometheus/prometheus"
          - "grpc-ecosystem/grpc-gateway"
          - "minio/minio"
          - "golangci/golangci-lint"
          - "istio/istio"
          - "argoproj/argo-cd"
          - "argoproj/argo-rollouts"
          - "argoproj/argo-events"
          - "ory/kratos"
          - "ory/hydra"
          - "ory/keto"
          - "grafana/loki"
          - "grafana/k6"
          - "grafana/tempo"
          - "grafana/agent"
          - "golang-migrate/migrate"
          - "terraform-linters/tflint"
          - "dapr/dapr"
          - "gomods/athens"
          - "future-architect/vuls"
          - "etcd-io/etcd"
          - "jaegertracing/jaeger"
          - "VictoriaMetrics/VictoriaMetrics"
          - "helm/helm"
          - "go-gitea/gitea"
          - "matrix-org/dendrite"
          - "rclone/rclone"
          - "tailscale/tailscale"
          - "uber/cadence"
          - "coredns/coredns"
          - "rook/rook"
          - "open-policy-agent/opa"
          - "nats-io/nats-server"
          - "spiffe/spire"
          - "thanos-io/thanos"
          - "buildpacks/pack"
          - "GoogleContainerTools/kaniko"
          - "GoogleContainerTools/skaffold"
          - "tektoncd/pipeline"
          - "knative/serving"
          - "aquasecurity/trivy"
          - "goreleaser/goreleaser"
          - "GoogleCloudPlatform/terraformer"
          - "rqlite/rqlite"
          - "go-delve/delve"
          - "cilium/cilium"
          - "containerd/containerd"
          - "projectcontour/contour"
          - "dgraph-io/badger"
          - "storj/storj"
          - "perkeep/perkeep"
          - "operator-framework/operator-sdk"
          - "openshift/oc"
          - "restic/restic"
          - "99designs/gqlgen"
          - "slackhq/nebula"
          - "schollz/croc"
          - "authelia/authelia"
          - "linkerd/linkerd2"
          - "containrrr/watchtower"
          - "rancher/rancher"
          - "projectdiscovery/httpx"
          - "ethereum/go-ethereum"
          - "fatedier/frp"
          - "caddyserver/caddy"
          - "nsqio/nsq"
    runs-on: ${{ matrix.os }}
    env:
      GOAMD64: ${{ matrix.go-amd64 }}
    steps:
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libsystemd-dev libbtrfs-dev libgpgme-dev librpm-dev
      - uses: actions/checkout@v2
        with:
          repository: ${{ matrix.target }}
          submodules: true
      - uses: WillAbides/setup-go-faster@v1
        with:
          go-version: ${{ matrix.go }}
      - name: print version and env info
        run: |
          go version
          go env
      - run: go build ./...
