name: build
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"
jobs:
  build-tip:
    runs-on: ubuntu-22.04
    outputs:
      sha: ${{ steps.sha.outputs.sha }}
    steps:
      - name: Get SHA
        id: sha
        run: |
          SHA=$(gh api 'repos/golang/go/commits?per_page=1' --jq '.[].sha')
          echo "SHA=$SHA" >> "$GITHUB_ENV"
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Download
        run: |
          curl -fsSL "https://github.com/golang/go/archive/$SHA.tar.gz" | tar zx
      - name: Create VERSION
        run: |
          echo "devel $SHA" > "go-$SHA/VERSION"
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run make.bash
        working-directory: go-${{ env.SHA }}/src
        run: |
          ./make.bash
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: go-${{ env.SHA }}
          path: go-${{ env.SHA }}
  build:
    needs:  [build-tip]
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: "juju/juju"
            deps: []
          - target: "kubernetes/ingress-nginx"
            deps: []
          - target: "hashicorp/terraform"
            deps: []
          - target: "hashicorp/consul"
            deps: []
          - target: "hashicorp/vault"
            deps: []
          - target: "hashicorp/nomad"
            deps: []
          - target: "hashicorp/packer"
            deps: []
          - target: "hashicorp/boundary"
            deps: []
          - target: "hashicorp/waypoint"
            deps: []
          - target: "prometheus/prometheus"
            deps: []
          - target: "grpc-ecosystem/grpc-gateway"
            deps: []
          - target: "minio/minio"
            deps: []
          - target: "golangci/golangci-lint"
            deps: []
          - target: "argoproj/argo-cd"
            deps: []
          - target: "argoproj/argo-rollouts"
            deps: []
          - target: "argoproj/argo-events"
            deps: []
          - target: "ory/kratos"
            deps: []
          - target: "ory/hydra"
            deps: []
          - target: "ory/keto"
            deps: []
          - target: "grafana/loki"
            deps: []
          - target: "grafana/k6"
            deps: []
          - target: "grafana/tempo"
            deps: []
          - target: "golang-migrate/migrate"
            deps: []
          - target: "terraform-linters/tflint"
            deps: []
          - target: "gomods/athens"
            deps: []
          - target: "future-architect/vuls"
            deps: []
          - target: "etcd-io/etcd"
            deps: []
          - target: "jaegertracing/jaeger"
            deps: []
          - target: "VictoriaMetrics/VictoriaMetrics"
            deps: []
          - target: "helm/helm"
            deps: []
          - target: "go-gitea/gitea"
            deps: []
          - target: "rclone/rclone"
            deps: []
          - target: "uber/cadence"
            deps: []
          - target: "coredns/coredns"
            deps: []
          - target: "rook/rook"
            deps: []
          - target: "open-policy-agent/opa"
            deps: []
          - target: "nats-io/nats-server"
            deps: []
          - target: "spiffe/spire"
            deps: []
          - target: "thanos-io/thanos"
            deps: []
          - target: "buildpacks/pack"
            deps: []
          - target: "GoogleContainerTools/kaniko"
            deps: []
          - target: "GoogleContainerTools/skaffold"
            deps: []
          - target: "tektoncd/pipeline"
            deps: []
          - target: "knative/serving"
            deps: []
          - target: "goreleaser/goreleaser"
            deps: []
          - target: "GoogleCloudPlatform/terraformer"
            deps: []
          - target: "rqlite/rqlite"
            deps: []
          - target: "go-delve/delve"
            deps: []
          - target: "cilium/cilium"
            deps: []
          - target: "containerd/containerd"
            deps: []
          - target: "projectcontour/contour"
            deps: []
          - target: "dgraph-io/badger"
            deps: []
          - target: "perkeep/perkeep"
            deps: []
          - target: "operator-framework/operator-sdk"
            deps: []
          - target: "openshift/oc"
            deps: []
          - target: "restic/restic"
            deps: []
          - target: "99designs/gqlgen"
            deps: []
          - target: "slackhq/nebula"
            deps: []
          - target: "schollz/croc"
            deps: []
          - target: "authelia/authelia"
            deps: []
          - target: "linkerd/linkerd2"
            deps: []
          - target: "containrrr/watchtower"
            deps: []
          - target: "projectdiscovery/httpx"
            deps: []
          - target: "ethereum/go-ethereum"
            deps: []
          - target: "nsqio/nsq"
            deps: []
          - target: "kedacore/keda"
            deps: []
          - target: "open-telemetry/opentelemetry-collector"
            deps: []
          - target: "gohugoio/hugo"
            deps: []
          - target: "derailed/k9s"
            deps: []
          - target: "cayleygraph/cayley"
            deps: []
          - target: "kubernetes/kops"
            deps: []
          - target: "gopherjs/gopherjs"
            deps: []
          - target: "quay/clair"
            deps: []
          - target: "codenotary/immudb"
            deps: []
          - target: "flannel-io/flannel"
            deps: []
          - target: "OWASP/Amass"
            deps: []
          - target: "weaveworks/ignite"
            deps: []
          - target: "concourse/concourse"
            deps: []
          - target: "vmware-tanzu/octant"
            deps: []
          - target: "moby/buildkit"
            deps: []
          - target: "tendermint/tendermint"
            deps: []
          - target: "runatlantis/atlantis"
            deps: []
          - target: "aquasecurity/tfsec"
            deps: []
          - target: "rh12503/triangula"
            deps: []
          - target: "emitter-io/emitter"
            deps: []
          - target: "benthosdev/benthos"
            deps: []
          - target: "cortexproject/cortex"
    runs-on: ubuntu-22.04
    env:
      GOAMD64: v3
      DEPS: ${{ join(matrix.deps, ' ') }}
      SHA: ${{ needs.build-tip.outputs.sha }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: go-${{ env.SHA }}
          path: go-${{ env.SHA }}
      - name: Add path
        run: |
          echo "$PWD/go-${{ env.SHA }}/bin" >> "$GITHUB_PATH"
      - name: Check version
        run: |
          go env
          go version
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.target }}
          submodules: true
      - run: go build ./...
