name: build
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"
jobs:
  build-tip:
    strategy:
      matrix:
        runner: ["ubuntu-24.04", "ubuntu-24.04-arm"]
    runs-on: ${{ matrix.runner }}
    outputs:
      sha: ${{ steps.sha.outputs.sha }}
    steps:
      - name: Get SHA
        id: sha
        run: |
          SHA=$(gh api 'repos/golang/go/commits?per_page=1' --jq '.[0].sha')
          echo "SHA=$SHA" >> "$GITHUB_ENV"
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: cache
        uses: actions/cache@v4
        id: cache-tip
        with:
          path: go-${{ env.SHA }}
          key: go-${{ env.SHA }}-${{ matrix.runner }}
      - uses: actions/setup-go@v5
        if: steps.cache-tip.outputs.cache-hit != 'true'
        with:
          go-version: '1.23'
      - name: build tip
        if: steps.cache-tip.outputs.cache-hit != 'true'
        run: |
          curl -fsSL "https://github.com/golang/go/archive/$SHA.tar.gz" | tar zx
          echo "devel $SHA" > "go-$SHA/VERSION"
          pushd "go-$SHA/src"
          ./make.bash
  build:
    needs: [build-tip]
    strategy:
      fail-fast: false
      matrix:
        runner: ["ubuntu-24.04", "ubuntu-24.04-arm"]
        target:
          - "99designs/gqlgen"
          - "GoogleCloudPlatform/terraformer"
          - "GoogleContainerTools/kaniko"
          - "GoogleContainerTools/skaffold"
          - "VictoriaMetrics/VictoriaMetrics"
          - "aquasecurity/tfsec"
          - "argoproj/argo-cd"
          - "authelia/authelia"
          - "buildpacks/pack"
          - "cilium/cilium"
          - "cloudflare/cloudflared"
          - "codenotary/immudb"
          - "concourse/concourse"
          - "containerd/containerd"
          - "containers/skopeo"
          - "containrrr/watchtower"
          - "coredns/coredns"
          - "cortexproject/cortex"
          - "derailed/k9s"
          - "dgraph-io/badger"
          - "emitter-io/emitter"
          - "etcd-io/etcd"
          - "ethereum/go-ethereum"
          - "flannel-io/flannel"
          - "future-architect/vuls"
          - "go-delve/delve"
          - "go-gitea/gitea"
          - "gohugoio/hugo"
          - "golang-migrate/migrate"
          - "golangci/golangci-lint"
          - "gomods/athens"
#         - "gopherjs/gopherjs"
          - "goreleaser/goreleaser"
          - "grafana/k6"
          - "grpc-ecosystem/grpc-gateway"
          - "hashicorp/boundary"
          - "hashicorp/consul"
          - "hashicorp/nomad"
          - "hashicorp/packer"
          - "hashicorp/terraform"
          - "hashicorp/vault"
          - "helm/helm"
          - "helmfile/helmfile"
          - "jaegertracing/jaeger"
          - "juju/juju"
          - "kedacore/keda"
          - "knative/serving"
          - "kopia/kopia"
          - "kubernetes/ingress-nginx"
          - "kubernetes/kops"
          - "linkerd/linkerd2"
          - "minio/minio"
          - "microsoft/typescript-go"
          - "moby/buildkit"
          - "nats-io/nats-server"
          - "nsqio/nsq"
          - "opencontainers/umoci"
          - "open-policy-agent/opa"
          - "open-telemetry/opentelemetry-collector"
          - "ory/hydra"
          - "ory/keto"
          - "ory/kratos"
          - "perkeep/perkeep"
          - "projectcontour/contour"
          - "projectdiscovery/httpx"
          - "prometheus/prometheus"
          - "quay/clair"
          - "rclone/rclone"
          - "redpanda-data/connect"
          - "restic/restic"
          - "rook/rook"
          - "rqlite/rqlite"
          - "runatlantis/atlantis"
          - "schollz/croc"
          - "spiffe/spire"
          - "tektoncd/pipeline"
          - "tendermint/tendermint"
          - "terraform-linters/tflint"
          - "thanos-io/thanos"
    runs-on: ${{ matrix.runner }}
    env:
      GOAMD64: v3
      SHA: ${{ needs.build-tip.outputs.sha }}
    steps:
      - name: download
        uses: actions/cache@v4
        with:
          path: go-${{ env.SHA }}
          key: go-${{ env.SHA }}-${{ matrix.runner }}
      - name: set env
        run: |
          echo "GOTIP=$PWD/go-${{ env.SHA }}/bin/go" >> "$GITHUB_ENV"
      - name: check version
        run: |
          "$GOTIP" version
          "$GOTIP" env
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.target }}
          submodules: true
          path: ${{ matrix.target }}
      - name: gotip build
        run: |
          "$GOTIP" build ./...
        working-directory: ${{ matrix.target }}
